### PR TITLE
Propose alternative navigation APIs. Strange ones.

### PR DESCRIPTION
**Pull request by dcampogiani**
Q: Why?
A: I don't like to pass activity as navigation parameter

Q: But you need it
A: I know, that's why I'm using extension

Q: You are going to pollute autocomplete adding a lot of methods to activity
A: Well ... we could add these extensions inside some classes

Q: And then how could you bring them in scope?
A: Glad you asked, we can use with() method in standard library

Q: This is no sense
A: **BUT IS WORKING**

Screenshot 2020-05-16 at 16 38 48

### CODE REVIEW

**Comment by dcampogiani** [comment]
You now owe me a Fortnite match with @Faber92 and @Donald90

**Comment by fchiusolo** [comment]
> You now owe me a Fortnite match with @Faber92 and @Donald90

Come on @ologe we need one more player to complete the team

**Review by Faber92 — APPROVED** [review]

**Comment by L-Andrade** [comment]
Is it possible for the Controller to have access to the Activity/Fragment via Dagger? I think it already has some bindings for it, and that way you could remove the extensions from the controller and directly inject it - this way it would at least remove the `with` from the Activity/Fragment. Might be a bad idea though?

Also, couldn't the navigation logic be inside the controller? I mean the `if (isLogged) ...` thing - but I guess that's not the point of the PR 😅 
```
fun FragmentActivity.navigate() = with(navigator) {
        if (isLogged()) toMain() else toLogin()
    }
```

**Comment by ologe** [comment]
@dcampogiani @L-Andrade 
yeah, I like more the solution proposed by Luis, where you simply inject the activity inside the `Controller`

**Comment by dcampogiani** [comment]
@ologe @L-Andrade then I can close this PR. But it was fun to do it.

**Pull request closed without merging**
